### ISSUE TITLE
Username under title missing css

### ISSUE THREAD

**Issue by joshkerr** [themeskult/wp-svbtle#48]
You are missing this css:

``` css
header#sidebar h1#blog_owner a {
font-family: "freight-sans-pro",sans-serif;
font-weight: 900;
letter-spacing: 1px;
font-size: 13px;
line-height: 16px;
border: none;
padding: 0;
display: block;
color: #585858;
margin-left: 0;
margin-bottom: 10px;
text-transform: uppercase;
}
```

Also, you shouldn't assume that the blog name is going to be the "first" and "last" name of the admin with the ID of 1.
