### ISSUE TITLE
Support for Disqus comments

### ISSUE THREAD

**Issue by joshkerr** [themeskult/wp-svbtle#51]
If you are going to support the built in Wordpress comments, you should support the disqus comment system as well.  You pretty much do support them, but you need to add a little CSS to add some padding, something like this:

``` css

.comments{
    padding-top: 50px;
    padding-left: 50px;
    padding-right: 50px;
}

```

Here is a screenshot:

![Screenshot](http://i.imgur.com/M6f9C.png)
